source "https://rubygems.org"

gem "monkrb", "~> 0.21", require: "monk"
gem "rackup"
gem "webrick"
gem "kino"
gem "dotenv" # loads .env files, see config/settings.rb

group :test do
  gem "minitest"
  gem "rake"
end
